### ISSUE TITLE
UnsatisfiedLinkError, no such file `libmkl_rt.so`, with `org.bytedeco/mkl-platform-redist` included as a dep.

### ISSUE THREAD

**Issue by eihli** [uncomplicate/neanderthal#102]
After reading the docs at https://neanderthal.uncomplicate.org/articles/getting_started.html#the-native-library-used-by-neanderthals-native-engine-optional I expected I wouldn't see an error about missing mkl-related files if I included the bytedeco dep.

But I'm getting this when I launch cider.

```
Execution error (UnsatisfiedLinkError) at java.lang.ClassLoader$NativeLibrary/load (ClassLoader.java:-2).
/tmp/libneanderthal-mkl-0.33.0724836737567557959.so: libmkl_rt.so: cannot open shared object file: No such file or directory
...
java.lang.NoClassDefFoundError: Could not initialize class uncomplicate.neanderthal.internal.host.MKL
```

deps.edn

```
{:paths ["src" "resources"]
 :deps {org.clojure/clojure {:mvn/version "1.10.1"}
        uncomplicate/neanderthal {:mvn/version "0.38.0"}
        org.bytedeco/mkl-platform-redist {:mvn/version "2020.1-1.5.3"}}
 :aliases {:dev {:extra-paths ["dev"]}}}
```

**Comment by blueberry** [comment]
You're probably using a mismatched version of javacpp-mkl. See the example hello world: https://github.com/uncomplicate/neanderthal/blob/master/examples/hello-world/project.clj

**Comment by eihli** [comment]
Ah yes. That was it. `mkl-platform-redist` @ `2020.3-1.5.4` and `neanderthal` @ `0.38.0` works. Thanks!

**Comment by zendevil** [comment]
This doesn't work for me. I'm still getting the error. Here's my project.clj, the same one in hello-world example. I'm running the hello world example from the source:

```
(defproject hello-world "0.38.0"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.10.1"]
                 [uncomplicate/neanderthal "0.38.0"]
                 ;;Optional. If bytedeco is not present, a system-wide MKL is used.
                 [org.bytedeco/mkl-platform-redist "2020.3-1.5.4"]]
  ;; Nvidia doesn't ship CUDA for macOS; you have to add this to your project
  :exclusions [[org.jcuda/jcuda-natives :classifier "apple-x86_64"]
               [org.jcuda/jcublas-natives :classifier "apple-x86_64"]]
  ;; If on Java 9+, you have to uncomment the following JVM option.
  :jvm-opts ^:replace [#_"--add-opens=java.base/jdk.internal.ref=ALL-UNNAMED"])

```

**Comment by burbma** [comment]
Alright I've got a lead on this but I'm in way over my head.

So `uncomplicate.neanderthal.native` requires `uncomplicate.neanderthal.internal.host.mkl`. The problem is running `(require '[uncomplicate.neanderthal.internal.host.mkl])` fails with something like:
```
Execution error (UnsatisfiedLinkError) at java.lang.ClassLoader$NativeLibrary/load0 (ClassLoader.java:-2).
/private/var/folders/8m/p0_shyw51mq8mf2bb7lg52yc0000gn/T/libneanderthal-mkl-0.33.010233505079158403947.jnilib: dlopen(/private/var/folders/8m/p0_shyw51mq8mf2b
b7lg52yc0000gn/T/libneanderthal-mkl-0.33.010233505079158403947.jnilib, 1): Library not loaded: @rpath/libmkl_intel_lp64.dylib
  Referenced from: /private/var/folders/8m/p0_shyw51mq8mf2bb7lg52yc0000gn/T/libneanderthal-mkl-0.33.010233505079158403947.jnilib
  Reason: image not found
```

After many searches and being generally out of my league I end up reading this https://blog.krzyzanowskim.com/2018/12/05/rpath-what/.

In that article I find that I can use `otool -l` to find out what this `@rpath` thing actually resolves to, it's tricky though because the binary `/private/var/folders/8m/p0_shyw51mq8mf2bb7lg52yc0000gn/T/libneanderthal-mkl-0.33.010233505079158403947.jnilib` only exists while my REPL is running and after I've tried the failing require. So in another shell I run `otool -l /private/var/folders/8m/p0_shyw51mq8mf2bb7lg52yc0000gn/T/libneanderthal-mkl-0.33.010233505079158403947.jnilib | grep -B 1 -A 2 LC_RPATH` and I get this:

```
Load command 15
          cmd LC_RPATH
      cmdsize 72
         path /opt/intel/compilers_and_libraries_2018.3.185/mac/mkl/lib (offset 12)
```

Which makes me think I wouldn't have issues if I installed MKL 2018.3.185 on my system, but I didn't, I'm using `org.bytedeco/mkl-platform-redist {:mvn/version "2020.3-1.5.4"}`. Seems strange that this rpath was set to such a specific install location, I'm not sure when this linking happens in Clojure/Java land or who has control over it.

Via previous searches and debug logs etc. I had already discovered that the dylib's are actually in `~/.javacpp/cache/mkl-2020.3-1.5.4-macosx-x86_64-redist.jar/org/bytedeco/mkl/macosx-x86_64/` so I simply tried copying them with:

```
sudo mkdir -p /opt/intel/compilers_and_libraries_2018.3.185/mac/mkl/lib
sudo cp ~/.javacpp/cache/mkl-2020.3-1.5.4-macosx-x86_64-redist.jar/org/bytedeco/mkl/macosx-x86_64/ /opt/intel/compilers_and_libraries_2018.3.185/mac/mkl/lib
```

And low and behold I can now `(require '[uncomplicate.neanderthal.internal.host.mkl])` as well as the original goal which was `(require '[uncomplicate.neanderthal.nativel])`. Running `(uncomplicate.neanderthal.native/dge 3 2 [1 2 3 4 5 6])` works as well.

I don't know where to go next as to tracking down what a more proper solution is than my copying of the dylib's.

cc people who seemed to have cared about this issue (or a potentially related one) in the past since conversations are spread out in multiple places:
@blueberry 
@zendevil 
@jasonwaack
@lccambiaghi
@Hendekagon
@SolbiatiAlessandro

**Comment by blueberry** [comment]
I don't know why you did all this, nor whether you've read the Getting Started guide, but it's great that you solved your issue at the end.

For posterity: I recommend reading Getting Started and proceeding accordingly.

**Comment by burbma** [comment]
Based on this issue and #31 I gathered that people were having trouble getting it to work in anyway besides installing mkl on the system and disabling SIP and exporting the right DYLD_LIBRARY_PATH. Yes I did read the starting guide, it claims one should be able to just include the bytedeco dependency:

> Final note If you prefer zero-install, just include [org.bytedeco/mkl-platform-redist "2020.3-1.5.4"] as a dependencly in your leiningen project and none of these is necessary.

But this statement is not true, you still need to copy the dylib's to the right place, either the one I used or perhaps /usr/local/lib which I haven't tried yet. The starting guide mentions making a copy to /usr/local/lib but I was under the impression based on the quote above that such would only be necessary for a system install of mkl and not when including the bytedeco dependency.

**Comment by blueberry** [comment]
> Based on this issue and #31 I gathered that people were having trouble getting it to work in anyway besides installing mkl on the system and disabling SIP and exporting the right DYLD_LIBRARY_PATH. Yes I did read the starting guide, it claims one should be able to just include the bytedeco dependency:
> 
> > Final note If you prefer zero-install, just include [org.bytedeco/mkl-platform-redist "2020.3-1.5.4"] as a dependencly in your leiningen project and none of these is necessary.
> 
> But this statement is not true (at least as I interpreted it), you still need to copy the dylib's to the right place, either the one I used or perhaps /usr/local/lib which I haven't tried yet. The starting guide mentions making a copy to /usr/local/lib but I was under the impression based on the quote above that such would only be necessary for a system install of mkl and not when including the bytedeco dependency.

You have to disable SIP, then everything works in the same way as linux, and that's it. Now, I understand that some people might have reasons why they don't want to disable SIP, but that's beyond what I can support. It's literally that there is a big Apple dam blocking the river, and people are complaining why there is no water downstream. There is no water because the dam (SIP) is blocking all water. If you don't want to open the dam, that's ok, but then I don't know how to help.

**Comment by burbma** [comment]
It's very possible that I'm still just missing something and I apologize if I'm being confusing in how I try to explain this.

I tried disabling SIP and including the bytedeco dependency but I still had the `Reason: image not found` error. Would you have expected those two steps alone to be sufficient?

**Comment by blueberry** [comment]
It should be. Please try the Hello World example project first https://github.com/uncomplicate/neanderthal/tree/master/examples/hello-world
Please read the comments in project.clj regarding Java 9+ and jvm-opts.

If that doesn't work, then it may be that there's something set up on your OS that messes with this, or Apple introduced yet another roadblock for developers. IDK. I only have an old MacBook Air, and no access to latest macOS. But I've helped quite a few people set up new macs and in each case when they had various issues the source of the problem was always SIP. Maybe that reconfiguration requires a reboot, who knows...

**Comment by burbma** [comment]
I've tried hello-world, using OpenJDK 11.0.9.1 and thus uncommenting the jvm-opts, I disabled SIP and rebooted, it gives the same error
```
Execution error (UnsatisfiedLinkError) at java.lang.ClassLoader$NativeLibrary/load0 (ClassLoader.java:-2).
/private/var/folders/8m/p0_shyw51mq8mf2bb7lg52yc0000gn/T/libneanderthal-mkl-0.33.013592419731879182342.jnilib: dlopen(/private/var/folders/8m/p0_shyw51mq8mf2bb7lg52yc0000gn/T/libneanderthal-mkl-0.33.013592419731879182342.jnilib, 1): Library not loaded: @rpath/libmkl_intel_lp64.dylib
  Referenced from: /private/var/folders/8m/p0_shyw51mq8mf2bb7lg52yc0000gn/T/libneanderthal-mkl-0.33.013592419731879182342.jnilib
  Reason: image not found
```

I appreciate your responses and don't expect you to resolve this for me. If you don't mind, I'm wondering if you know any details about this file and where it comes from `/private/var/folders/8m/p0_shyw51mq8mf2bb7lg52yc0000gn/T/libneanderthal-mkl-0.33.013592419731879182342.jnilib`. It seems to be created once I attempt to require uncomplicate.neanderthal.internal.host.mkl and it is the library that when loaded by dlopen fails to find it's dependency on the mkl dylib's.

**Comment by blueberry** [comment]
Then it seems that this deserves its own issue. Please create a new with as many detailed info as you can share. I really don't know what could be the problem, nor I have a machine when I could reproduce it, but someone else might help. In the meantime, I guess some other installation option might be a temporary workaround.

**Comment by malloc82** [comment]
@burbma I don't know if you have solved this, but I ran into the same problem and was able to fix it. It seems like the mkl redist library is missing libmkl_intel_lp64.dylib file which is supposed to link to libmkl_intel_lp64.1.dylib. I just manually created the link in the same folder in addition to creating a link of /opt/intel/compilers_and_libraries_2018.3.185/mac/mkl/lib that points to the  ~/.javacpp/cache/mkl-2020.3-1.5.4-macosx-x86_64-redist.jar/org/bytedeco/mkl/macosx-x86_64/. That seems to fixed the problem. 

@blueberry I think the redist mkl library is supposed to work out of the box, but I think they missed a hard link which requires user to manually set it up.

**Comment by vxe** [comment]
I also could not get the redist mkl library to work however the install the intel libs worked, I did the following (macos):

1. install intel mkl via gui (make a note of version)  [link](https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-download.html?operatingsystem=mac&distributions=webdownload&options=online)

2. set DYLD_LIBRARY_PATH
```
 export  DYLD_LIBRARY_PATH=/opt/intel/oneapi/mkl/VERSION_FROM_STEP_1/lib    
```

3. try lein repl

```
➛ DYLD_LIBRARY_PATH=/opt/intel/oneapi/mkl/2022.0.0/lib lein repl                                                                                                                                                        3:29AM 02-04-2022
OpenJDK 64-Bit Server VM warning: -XX:+UseLargePages not supported in this VM
nREPL server started on port 55698 on host 127.0.0.1 - nrepl://127.0.0.1:55698
REPL-y 0.5.1, nREPL 0.8.3
Clojure 1.10.3
OpenJDK 64-Bit Server VM 17+0
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (ns hello-world.native
  #_=> (:require [uncomplicate.neanderthal
  #_=>              [core :refer :all]
  #_=>              [native :refer :all]]))
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
nil
hello-world.native=> (def a (dge 2 3 [1 2 3 4 5 6]))
#'hello-world.native/a
hello-world.native=> (def b (dge 3 2 [1 3 5 7 9 11]))
#'hello-world.native/b
hello-world.native=> (mm a b)
#RealGEMatrix[double, mxn:2x2, layout:column, offset:0]
   ▥       ↓       ↓       ┓    
   →      35.00   89.00         
   →      44.00  116.00         
   ┗                       ┛    
```

**Comment by vxe** [comment]
2021.1 mkl no longer available on intel site, can download here and set `DYLD_LIBRARY_PATH` as above

* https://anaconda.org/intel/mkl/files?version=2021.1.1
