### ISSUE TITLE
Sulong for native interop?

### ISSUE THREAD

**Issue by kovasb** [uncomplicate/neanderthal#21]
Sulong (https://github.com/graalvm/sulong) will run on unmodified JVM in Java 9. It is the basis for native extension interop for JRuby/Truffle. Full paper at http://ssw.jku.at/General/Staff/ManuelRigger/VMIL16.pdf

They make several claims regarding their FFI: 1) 0-overhead calls into native, 2) inlining of native calls. This is in addition to their primary claim of interpreting LLVM bitcode at seeds comparable to gcc o3.

This might be interesting for a) Neanderthal's FFI, and b) particularly as an evolution of Fluokitten. Once a higher-level matrix operation has been specified, one can write a Truffle interpreter for that operation in terms of the Sulong LLVM interpreter. And have that specialize down to the fastest thing possible. 

I'm not exactly sure how it would relate to the OpenCL / Cuda side of things though. 

Would be curious what you think (if this would be a useful technology to look at for these sorts of things)

**Comment by blueberry** [comment]
JNI is pretty much hard to beat performance-wise I think. Why? Because the overhead, when JNI is done right, and in cases when this is possible, is miniscule compared to the runtime of vectorized (matrix-related) operations, even for small matrices (as you can see in neanderthal benchmarks). When JNI overhead would matter, in scalar function calls, I doubt that platform independent C is faster than Clojure/Java. Where C could make a difference, is in (platform-dependent) AVX or SSE operations, but those are useful only when you have arrays, thus rarely (or not at all) scalar stuff, and the C code is far from simple and portable in those cases.

For OpenCL/CUDA, the FFI overhead is much, much, smaller than driver overhead, so I doubt that this part could see any noticeable benefits.

Of course, this might be stuff that is worth keeping eye on in the future.

I think that for the time being, near, and even mid-term future, the top priority should be covering BLAS/LAPACK features, integrating some sparse and FFT native libraries, and creating ClojureCUDA and ClojureDNN (although the last two are related to nvidia's proprietary technology, so I will probably keep those two closed and provide them only on commercial basis and/or as a part of consulting contracts).

**Comment by kovasb** [comment]
Thanks for the perspective. 

I guess the notion is to make it easier to write high-performance code in Clojure. Though theoretically its possible, it requires great case to maintain some abstraction capability, hence solutions like Fluokitten. 

Its understandable priorities are different: I'm interested in more general tensor manipulation a la torch's stdlib, rather than primarily interop with particular already-optimized libraries. 

Looking forward to watching your Euroclojure video!

**Comment by blueberry** [comment]
The point is that I am not sure whether that code would be (much?) faster than what's currently possible in Clojure. Sulong has not yet been released, it looks to me. There is experimental code - have you tried building it and what performance did you get?

**Comment by blueberry** [comment]
BTW, you can see the slides for my talk at http://dragan.rocks, and I hope you'll like the talk when it's released. I am also looking forward to that video :)
