### ISSUE TITLE
Comparison with netlib-java

### ISSUE THREAD

**Issue by alexandergunnarson** [uncomplicate/neanderthal#22]
This looks like an amazing library! I'm definitely convinced that this has better performance than Vectorz or Jblas, but what about a comparison with [netlib-java](https://github.com/fommil/netlib-java)? I've tried looking around for more recent benchmarks on netlib-java than the [2009 ones I found](http://blog.mikiobraun.de/2009/04/some-benchmark-numbers-for-jblas.html) but I can't find any.

Thanks for your time!

**Comment by blueberry** [comment]
Thank you! 

Here's how it works: Neanderthal has a very minimal overhead, and I doubt that netlib-java can go faster from the code that I looked at. Also, netlib-java tries to integrate every library available transparently, so the first challenge when using it is to even make sure that the fast implementation has been used, instead of one of the slower fallback. Even if they are of the same speed, there is a crucial thing: Neanderthal is written in Clojure, has a fine Clojure API, and has fine-grained support for GPU computing. It also fits well with ClojureCL for custom GPU and optimized CPU algoritms. With netlib-java, you have a bloated java library, that is still awkward to use from Clojure.

As for benchmarks, I'd love if you did those, but, frankly, I don't expect to see any useful information since Neanderthal is practically as fast as the backends that it uses, and it is always clear which backend has been used.

I've put enough time in exploring this space in detail, that I'm pretty confident that it's time to concentrate on the feature completeness and better documentation, more tutorials, and building tools on top of it. I think that I have convincing data to show Neanderthal's strengths, so I'll leave other developers throw it in challenging situation, and try to find something better :)

Please, if you find some benchmarks, or do your own, please reopen this issue, and I'll see to include it in the official documentation.

**Comment by alexandergunnarson** [comment]
Thanks so much for your quick and detailed reply!

> Even if they are of the same speed, there is a crucial thing: Neanderthal is written in Clojure, has a fine Clojure API, and has fine-grained support for GPU computing.

I definitely agree with this part, and that's one of the (several) things that drew me to Neanderthal in the first place. I suppose my question stems from a desire to have the benefits of both *fast* and *feature-rich*. It seems that you have the "fast" part down better than any library of its kind, which is amazing in and of itself. As for the "feature-rich" part, I see that you've completely taken care of BLAS, and that LAPACK is ["currently on the TODO list"](https://github.com/uncomplicate/neanderthal/blob/e14d485060e9d590514ca83fbfa0652663b3b4a5/test/uncomplicate/neanderthal/examples/guides/tutorial_native_test.clj) (yay! 🎉). That said, I'd love to use your library in higher-level contexts () as well while being confident that I'm getting the best performance I can get. That's why I've considered `core.matrix` and even `breeze` or `matrix-toolkits-java`. What are your plans in terms of higher-level operations with your library? I don't necessarily want to roll my own higher-level operations with your BLAS wrapper (though I could I suppose), because I suspect that the performance of e.g. `matrix-toolkits-java` (which relies on `netlib-java`) would exceed the performance I could eke out of a naive implementation of those operations even using Neanderthal. Might making Neanderthal a backend to `core.matrix` be the answer? Just brainstorming here while trying to do as little wheel-reinventing as makes sense.

**Comment by blueberry** [comment]
Well, you know how it goes with open-source: if something you need isn't there, you can always contribute yourself, or wait for those who fund the development to add it because they need it :)

I am committed to these projects, and have means to fund them for a long, long time, so they will be continuously improved, but I can't (and won't) promise when some specific functionality will be on the menu.

**Comment by alexandergunnarson** [comment]
Just so you know, what I said wasn't meant to be an implicit "do this for me" haha :) It was more of a question of, "What are your long-term plans?" so I can plan accordingly and not reinvent the wheel, while leveraging your library if possible. I'd love to create a Clojure version of Spark's `mllib`  which uses your library, but I'm still trying to gauge whether it would be better to just create Clojure bindings for `mllib` and eat the performance degradation between it and your library, versus spend the effort to use your (great!) library perhaps in conjunction with code from `core.matrix` or something to create the higher-level functions I need.

Anyway, thanks!

**Comment by blueberry** [comment]
Of course. I didn't mean to imply that. I wanted to encourage you to contribute.

**Comment by alexandergunnarson** [comment]
You didn't imply that - I just wanted to make sure that you knew I wasn't being rude haha. But thank you for your graciousness! Contributions may be forthcoming, depending :)
