### ISSUE TITLE
Error building classpath. Could not find artifact org.jcuda:jcublas:jar:10.2.0 in central (https://repo1.maven.org/maven2/)

### ISSUE THREAD

**Issue by ftravers** [uncomplicate/neanderthal#84]
trying to build and thats what I got

Error building classpath. Could not find artifact org.jcuda:jcublas:jar:10.2.0 in central (https://repo1.maven.org/maven2/)

**Comment by blueberry** [comment]
Yes, JCuda 10.2 still hasn't reached the central Maven repository. I may have rushed a bit with the release because I had some time to spare yesterday, but expect it to work out of the box in a matter of days https://github.com/jcuda/jcuda-main/issues/31

Alternatively, in the meantime, use 0.26.1 w/ CUDA 10.1, or build JCuda 10.2, or if you are on Linux, grab JCuda binaries from the aforementioned link.

**Comment by blueberry** [comment]
JCuda 10.2.0 is in the Central Maven Repository, so this should work as expected.

**Comment by zendevil** [comment]
Got this error today.
