### ISSUE TITLE
Integer matrices on MKL?

### ISSUE THREAD

**Issue by chrysophylax** [uncomplicate/neanderthal#99]
Hi,

I am looking at working with dense matrices containing exclusively integers using MKL.
I have been unable to do it using neanderthal - am I missing something or are they just not implemented?
I keep hitting on AbstractMethodError which makes me think they're not linked in yet. 

I am not sure how to go about adding it myself unfortunately.

**Comment by blueberry** [comment]
MKL and other low-level libraries do not provide operations for integer-based matrices and vectors. There is a reason: as soon as your matrix contains many entries, and as soon as these entries become large-ish there is a large chance of integer overflow. Why floating point matrices are not good for your use case?

**Comment by chrysophylax** [comment]
Yes, we can overflow but MKL does provide extensions to BLAS that operate on integer-based matrices that work well. 
Here's the link to MKL developer reference
[cblas_gemm_*  Computes a matrix-matrix product with general integer matrices.](https://software.intel.com/content/www/us/en/develop/documentation/mkl-developer-reference-c/top/blas-and-sparse-blas-routines/blas-like-extensions/cblas-gemm-1.html)

VNNI extensions make it pretty fast to do some calculations with mkl-int.
![image](https://user-images.githubusercontent.com/10576351/93363764-37b94580-f837-11ea-9b36-157ea3ed75b5.png)

All in all, you can get better throughput, lower memory usage, lower power usage in exchange for an acceptable loss of precision.

It is not "super-necessary" I would say, I can work with fp but I'd like to see neanderthal support it.

**Comment by blueberry** [comment]
The gemm_* you linked to can compute some integer types, but then the problem is what to do with all other operations, which still stay unimplemented. Please also note that current hardware is optimized for floats. Integers may have use in some special applications, but then you'll have to have AVX_512, and shorter, 1 or 2 byte integers to see any benefits.

OTOH, Deep Diamond supports inner product supports (some) integers, so that may be what you're looking for.
